version: "3.9"
services:

  frontend:
    image: node:16.18-alpine
    entrypoint: ["yarn" , "start"]
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    volumes: 
      - ./frontend:/app
    ports: 
      - 3000:3000

  backend:
    image: node:16.18.0-alpine
    entrypoint: ["/bin/sh", "-c", "yarn build && yarn start:dev --preserveWatchOutput"]
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    volumes: 
      - ./backend:/app
    ports: 
      - 3001:8080