name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: uzh-nft-2022
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uzh-nft-2022"
          heroku_email: "saitejareddy.pottanigari@uzh.ch"
          appdir: "backend"
          procfile: "web: yarn start:prod"
        env:
          HD_ACCESS_TOKEN_ADDRESS: "0xE2C9eB07Ed48141fAdCC4F26c2f4eBC03eE9Eac4"
          HD_NFT_TOKEN_ADDRESS: "0xC7a2BC8a9fF5D825535D71A264A867918F35501b"
          HD_ADMIN_PRIVATEKEY: ${{secrets.ADMIN_PRIVATEKEY}}
          HD_NETWORK_URL: https://vm-216.s3it.uzh.ch
          HD_IPFS_PROJECT_ID: 2Gd4nFIxYSa4JETkJde7OibyJQp
          HD_IPFS_PROJECT_SECRET: ${{secrets.IPFS_SECRET}}

    
          
