name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: uzh-nft-2022
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uzh-nft-2022"
          heroku_email: "saitejareddy.pottanigari@uzh.ch"
          appdir: "backend"
          procfile: "web: yarn start:prod"
        env:
          HD_ACCESS_TOKEN_ADDRESS: "0x0a039D3524a741cA71Ac6572Fbf388bD46F704Fa"
          HD_NFT_TOKEN_ADDRESS: "0x6de10EAe8b902F9C7cc03C72Ca477A6346508e5D"
          HD_ADMIN_PRIVATEKEY: ${{secrets.ADMIN_PRIVATEKEY}}
          HD_NETWORK_URL: http://130.60.24.200:8545
          HD_IPFS_PROJECT_ID: 2Gd4nFIxYSa4JETkJde7OibyJQp
          HD_IPFS_PROJECT_SECRET: ${{secrets.IPFS_SECRET}}

    
          
