name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: uzh-nft-2022
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uzh-nft-2022"
          heroku_email: "saitejareddy.pottanigari@uzh.ch"
          appdir: "backend"
          procfile: "web: yarn start:prod"
        env:
          HD_ACCESS_TOKEN_ADDRESS: "0x4D0906955AC7e68588463A13f9bFe81b7D32978D"
          HD_NFT_TOKEN_ADDRESS: "0x3EE02CCC4Ac0874B691687CeC8792F163d6427d1"
          HD_ADMIN_PRIVATEKEY: ${{secrets.ADMIN_PRIVATEKEY}}
          HD_NETWORK_URL: https://rpc.uzheths.ifi.uzh.ch
          HD_IPFS_PROJECT_ID: 2Gd4nFIxYSa4JETkJde7OibyJQp
          HD_IPFS_PROJECT_SECRET: ${{secrets.IPFS_SECRET}}

    
          
